package edu.gvsu.cis.kmpfirebase

import kotlinx.serialization.Serializable

@Serializable
data class City(
    val id: String = "",
    val name: String, val population: Int)

val randomCities: List<String> = kotlin.collections.listOf(
    "New York",
    "Los Angeles",
    "Chicago",
    "Houston",
    "Phoenix",
    "Philadelphia",
    "San Antonio",
    "San Diego",
    "Dallas",
    "San Jose",
    "Austin",
    "Jacksonville",
    "Fort Worth",
    "Columbus",
    "Charlotte",
    "San Francisco",
    "Indianapolis",
    "Seattle",
    "Denver",
    "Washington",
    "Boston",
    "El Paso",
    "Nashville",
    "Detroit",
    "Oklahoma City",
    "Portland",
    "Las Vegas",
    "Memphis",
    "Louisville",
    "Baltimore",
    "Milwaukee",
    "Albuquerque",
    "Tucson",
    "Fresno",
    "Sacramento",
    "Mesa",
    "Kansas City",
    "Atlanta",
    "Long Beach",
    "Omaha",
    "Raleigh",
    "Colorado Springs",
    "Miami",
    "Virginia Beach",
    "Oakland",
    "Minneapolis",
    "Tulsa",
    "Arlington",
    "New Orleans",
    "Wichita",
    "Aurora",
    "Tampa",
    "Santa Ana",
    "St. Louis",
    "Pittsburgh",
    "Corpus Christi",
    "Riverside",
    "Cincinnati",
    "Lexington",
    "Anchorage",
    "Stockton",
    "Toledo",
    "Saint Paul",
    "Newark",
    "Greensboro",
    "Buffalo",
    "Plano",
    "Lincoln",
    "Henderson",
    "Fort Wayne",
    "Jersey City",
    "St. Petersburg",
    "Chula Vista",
    "Irvine",
    "Orlando",
    "Laredo",
    "Lubbock",
    "Madison",
    "Gilbert",
    "Reno",
    "Glendale",
    "Chandler",
    "Winston-Salem",
    "North Las Vegas",
    "Scottsdale",
    "Irving",
    "Chesapeake",
    "Durham",
    "Fremont",
    "San Bernardino",
    "Paradise",
    "Hialeah",
    "Gilbert",
    "Wheaton",
    "Grand Rapids",
    "Grand Prairie",
    "Salt Lake City",
    "Huntsville",
    "Tallahassee",
    "Knoxville"
)

val randomMovies = listOf<String>(
    "The Shawshank Redemption",
    "The Godfather",
    "The Dark Knight",
    "The Godfather Part II",
    "12 Angry Men",
    "Schindler's List",
    "The Lord of the Rings: The Return of the King",
    "Pulp Fiction",
    "The Lord of the Rings: The Fellowship of the Ring",
    "The Good, the Bad and the Ugly",
    "Forrest Gump",
    "Fight Club",
    "Inception",
    "The Lord of the Rings: The Two Towers",
    "Star Wars: Episode V - The Empire Strikes Back",
    "The Matrix",
    "Goodfellas",
    "One Flew Over the Cuckoo's Nest",
    "Seven Samurai",
    "Se7en",
    "The Silence of the Lambs",
    "City of God",
    "It's a Wonderful Life",
    "Life Is Beautiful",
    "Saving Private Ryan",
    "Star Wars: Episode IV - A New Hope",
    "Interstellar",
    "Spirited Away",
    "The Green Mile",
    "Parasite",
    "Léon: The Professional",
    "The Usual Suspects",
    "Harakiri",
    "The Lion King",
    "The Pianist",
    "Back to the Future",
    "Terminator 2: Judgment Day",
    "American History X",
    "Modern Times",
    "Gladiator",
    "Psycho",
    "The Departed",
    "City Lights",
    "Untouchable",
    "Whiplash",
    "The Prestige",
    "Once Upon a Time in the West",
    "Grave of the Fireflies",
    "Casablanca",
    "Rear Window",
    "Cinema Paradiso",
    "Alien",
    "Apocalypse Now",
    "Memento",
    "Raiders of the Lost Ark",
    "The Great Dictator",
    "Django Unchained",
    "The Lives of Others",
    "Paths of Glory",
    "Sunset Blvd.",
    "WALL·E",
    "Avengers: Infinity War",
    "The Shining",
    "Witness for the Prosecution",
    "Spider-Man: Into the Spider-Verse",
    "Dr. Strangelove",
    "Joker",
    "Oldboy",
    "Princess Mononoke",
    "Your Name.",
    "The Dark Knight Rises",
    "Aliens",
    "Once Upon a Time in America",
    "Coco",
    "American Beauty",
    "Braveheart",
    "Das Boot",
    "3 Idiots",
    "Toy Story",
    "High and Low",
    "Amadeus",
    "Star Wars: Episode VI - Return of the Jedi",
    "Inglourious Basterds",
    "Good Will Hunting",
    "Reservoir Dogs",
    "2001: A Space Odyssey",
    "Requiem for a Dream",
    "Vertigo",
    "M",
    "Eternal Sunshine of the Spotless Mind",
    "Citizen Kane",
    "The Hunt",
    "Full Metal Jacket",
    "Bicycle Thieves",
    "The Kid",
    "Singin' in the Rain",
    "North by Northwest",
    "Snatch",
    "A Clockwork Orange",
    "Taxi Driver"
)